

# ###################################################################
# SERVICES
# ###################################################################
services:
  organize-tool:
    image: zorbatherainy/misc_images:organize-tool-latest
    container_name: organize-tool-croned
    restart: unless-stopped
    volumes:
      - ./organize-tool-crontab:/etc/cron.d/organize-tool-crontab   # mount your crontab file here
      - ./config.yaml:/config/config.yaml  # organize-tool config file
      - ./data:/data # the directory you wish organized
